#!/usr/bin/env python3
"""Emit LaTeX rows for the 4-way baselines table from interleaved_summary.csv.

Also prints paired per-repeat speedup ratios (t-based 95% CI) from
interleaved_raw_runs.csv for the 25q cells: Aer/mettleq, PL/mettleq, Aer/metal,
PL/metal, mettleq/metal.
"""
from __future__ import annotations

import csv
import math
import statistics
import sys
from pathlib import Path

LABELS = {
    "qft": "QFT",
    "qaoa_ring": "Ring-QAOA schedule",
    "tfim_trotter": "TFIM Trotter (20 steps)",
    "phase_estimation": "Phase estimation",
    "grover_proxy": "Grover proxy (1 iter.)",
    "ghz": "GHZ",
}
ORDER = ["qft", "qaoa_ring", "tfim_trotter", "phase_estimation",
         "grover_proxy", "ghz"]
BACKENDS = ["mettleq", "mettleq_metal", "pennylane", "aer"]
T9 = 2.262


def fmt(mean_ms: float, ci_ms: float) -> str:
    m, c = mean_ms / 1000.0, ci_ms / 1000.0
    if m >= 1:
        return f"${m:.3f} \\pm {c:.3f}$"
    if m >= 0.01:
        return f"${m:.4f} \\pm {c:.4f}$"
    return f"${m:.5f} \\pm {c:.5f}$"


def main() -> int:
    outdir = Path(sys.argv[1])
    rows = {}
    with (outdir / "interleaved_summary.csv").open() as fh:
        for r in csv.DictReader(fh):
            backend = r["backend"].replace("mlxq", "mettleq")
            rows[(r["benchmark"], int(r["qubits"]), backend)] = (
                float(r["mean_ms"]), float(r["ci95_ms"]))
    print("% generated by tools/gen_4way_table.py from", outdir)
    for bench in ORDER:
        for n in (15, 20, 25):
            cells = []
            for b in BACKENDS:
                m, c = rows[(bench, n, b)]
                cells.append(fmt(m, c))
            print(f"{LABELS[bench]} & {n} & " + " & ".join(cells) + " \\\\")

    raw = {}
    with (outdir / "interleaved_raw_runs.csv").open() as fh:
        for r in csv.DictReader(fh):
            backend = r["backend"].replace("mlxq", "mettleq")
            raw.setdefault((r["benchmark"], int(r["qubits"]), backend),
                           []).append(float(r["wall_ms"]))
    print("\n% paired per-repeat ratios at 25q (t-based 95% CI):")
    for bench in ORDER:
        out = [bench]
        for num, den, tag in [("aer", "mettleq", "Aer/MettleQ"),
                               ("pennylane", "mettleq", "PL/MettleQ"),
                               ("aer", "mettleq_metal", "Aer/metal"),
                               ("pennylane", "mettleq_metal", "PL/metal"),
                               ("mettleq", "mettleq_metal", "MettleQ/Metal")]:
            a = raw[(bench, 25, num)]
            b = raw[(bench, 25, den)]
            ratios = [x / y for x, y in zip(a, b)]
            mu = statistics.fmean(ratios)
            ci = T9 * statistics.stdev(ratios) / math.sqrt(len(ratios))
            out.append(f"{tag} {mu:.2f}+/-{ci:.2f}")
        print("  " + "  ".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
